server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_vux38?useSSL=false&serverTimezone=UTC
    username: root
    password: Sa12
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
  rabbitmq:
    host: localhost

user:
  service:
    url: http://localhost:8082

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration-ms: 86400000

logging:
  level:
    com.vux38.auth: DEBUG
    com.vux38.auth.client: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full